# Generated by Django 5.0.2 on 2024-03-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priec',
            new_name='price',
        ),
    ]
