# Generated by Django 5.0.2 on 2024-04-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
